module.exports = {
  RED: 'red',
  BLUE: 'blue',
  GREEN: 'green',
  PINK: 'pink',
  ORANGE: 'orange',
  YELLOW: 'yellow',
  BLACK: 'black',
  WHITE: 'white',
  PURPLE: 'purple',
  BROWN: 'brown',
  CYAN: 'cyan',
  LIME: 'lime',
  BANANA: 'banana',
  ROSE: 'rose',
  CORAL: 'coral',
  GRAY: 'gray',
  MAROON: 'maroon',
  TAN: 'tan'
}